name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          python3 -m pip install --upgrade pip
          # Cython નું ચોક્કસ વર્ઝન ઇન્સ્ટોલ કરવું જરૂરી છે
          pip install "cython<3.0" buildozer 

      - name: Build Android APK
        run: |
          # લોગ લેવલ ૨ સાથે રન કરો જેથી સાચી એરર દેખાય
          yes | buildozer -v android debug
