name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool libtool-bin m4 pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          python3 -m pip install --upgrade pip
          # બિલ્ડોઝર અને સાયથન સાથે પ્લેટફોર્મ ટૂલ્સ પણ ઇન્સ્ટોલ કરો
          pip install "cython<3.0" buildozer python-for-android

      - name: Build Android APK
        run: |
          # સીધું જ બિલ્ડ શરૂ કરો, ક્લીન કરવાની જરૂર નથી જો પહેલી વાર હોય
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TradingApp-APK
          path: bin/*.apk
